channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - django
  - ibis-framework
  - flake8
  - hatch
  - nox
  - pre-commit
  - psycopg2-binary
  - pydantic
  - pytest
  - sqlalchemy
  - sqlmodel
  - nodejs